Repository lzim/teampsd, pull requests merged in 2018-09, with the labels that each got.

#132 Update team4 post email
  mtl_facilitate_workgroup/pre_post_emails/team4/team4_post_2018_08_31.rmd
Labels: code_review, help_wanted

#130 Update team1_post_2018.08.15.rmd
  mtl_facilitate_workgroup/pre_post_emails/team1/team1_post_2018.08.15.rmd
Labels: code_review, help_wanted

#166 mtl_live_guide
  resources/mtl_live_guide/README.rmd
Labels: help_wanted

#204 Update mtl_live_session01_see.Rmd
  mtl_facilitate_workgroup/mtl_live_guide/mtl_live_session01_see.Rmd
  mtl_facilitate_workgroup/mtl_live_guide/mtl_live_session10_see.Rmd
Labels: code_review
