Repository lzim/teampsd, pull requests merged in 2019-06, with the labels that each got.

#366 Update inter_session_checklist.md
  mtl_facilitate_workgroup/checklists/inter_session_checklist.md
Labels: code_review

#376 Update mtl_session02_say.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session02_say.md
Labels: decision_made

#377 Update inter_session_checklist.md
  mtl_facilitate_workgroup/checklists/inter_session_checklist.md
Labels: decision_made

#432 Changed variables to match updated ModelParameter
  quant_workgroup/tt_report/tt3_agg.md
  quant_workgroup/tt_report/tt3_cc.md
  quant_workgroup/tt_report/tt3_mm.md
  quant_workgroup/tt_report/tt3_psy.md
  quant_workgroup/tt_report/tt3_sp.md
Labels: bug, quant, tt_report
