Repository lzim/teampsd, pull requests merged in 2020-02, with the labels that each got.

#974 Create red_part_1.md
  mtl_facilitate_workgroup/facilitator_say/mtl_red_part_1_say.md
  mtl_facilitate_workgroup/facilitator_say/mtl_red_part_2_say.md
Labels: document

#990 Update mtl_session04_say.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session04_say.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session05_say.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session06_say.md
Labels: document

#992 Update issue.md to reflect label ideology change
  .github/ISSUE_TEMPLATE/issue.md
Labels: hq

#1008 Rita 2020 02 18
  mtl_facilitate_workgroup/facilitator_say/mtl_session06_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session07_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session08_say.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session08_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session09_say.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session09_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session10_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session11_say.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session12_say.md
Labels: facilitate

#1016 Update mtl_session02_say.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session02_say.md
Labels: hq

#1026 Map of Documentation Process
  resources/maps/MTL Document Flow.pdf
Labels: hq
