Repository lzim/teampsd, pull requests merged in 2020-04, with the labels that each got.

#1285 Rita 2020 04 06 small circle headshots
  resources/small_circle_headshots/README.md
  resources/small_circle_headshots/branscomb_headshot_circle.jpg
  resources/small_circle_headshots/moore_headshot_circle.jpg
  resources/vapor_team_youtube/README.md
  resources/vapor_team_youtube/edwards_vapor.jpg
  resources/vapor_team_youtube/thompson_vapor.jpg
Labels: facilitate

#1283 Rita 2020 04 06 additional specs tt report
  resources/training_guides/emails_outlook/tt_teampsd.md
Labels: hq

#1284 Rita 2020 04 02 logos pre post emails
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session01.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session02.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session03.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session04.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session05.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session06.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session07.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session08.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session09.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session10.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session11.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session12.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session01.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session02.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session03.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session04.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session05.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session06.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session07.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session08.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session09.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session10.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session11.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session12.md
Labels: hq

#1326 Update tt_teampsd.md
  resources/training_guides/emails_outlook/tt_teampsd.md
Labels: hq

#1298 Rita 2020 04 09 remaining images for email templates
  resources/logos/tms_logo.jpg
  resources/small_circle_headshots/collie_headshot_circle.jpg
  resources/small_circle_headshots/hunt_headshot_circle.jpg
  resources/small_circle_headshots/iwamasa_headshot_circle.jpg
  resources/small_circle_headshots/kibbe_headshot_circle.jpg
  resources/small_circle_headshots/klocek_headshot_circle.jpg
  resources/small_circle_headshots/lounsbury_headshot_circle.jpg
  resources/small_circle_headshots/rust_headshot_circle.jpg
  resources/small_circle_headshots/schmitz_headshot_circle.jpg
  resources/vapor_team_youtube/barlow_vapor.jpg
  resources/vapor_team_youtube/kramer_vapor.jpg
  resources/vapor_team_youtube/ontiveros_vapor.jpg
Labels: facilitate

#1328 Add files via upload
  resources/cheatsheets/mtl_how_data_cheatsheet.pdf
Labels: hq

#1341 Update feature.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: hq, quant, sim_ui

#1342 Update issue.md
  .github/ISSUE_TEMPLATE/issue.md
Labels: hq, quant, sim_ui

#1346 Update tt_teampsd.md
  resources/training_guides/emails_outlook/tt_teampsd.md
Labels: hq

#1355 Create readme.md
  resources/title_slides/svg/readme.md
Labels: pi

#1356 Add files via upload
  resources/title_slides/svg/mtl_s01_teamvision_title.svg
  resources/title_slides/svg/mtl_s02_data_ui_title.svg
  resources/title_slides/svg/mtl_s03_teamdata_title.svg
  resources/title_slides/svg/mtl_s04_teamneeds_title.svg
  resources/title_slides/svg/mtl_s05_teamworld_title.svg
  resources/title_slides/svg/mtl_s06_systems_story_title.svg
  resources/title_slides/svg/mtl_s07_base_case_title.svg
  resources/title_slides/svg/mtl_s08_dynamic_hypothesis_title.svg
  resources/title_slides/svg/mtl_s09_compare_alternatives_title.svg
  resources/title_slides/svg/mtl_s10_systems_thinking_title.svg
  resources/title_slides/svg/mtl_s11_team_decisions_title.svg
  resources/title_slides/svg/mtl_s12_team_plan_title.svg
Labels: pi

#1358 Add files via upload
  resources/title_slides/ai/mtl_s01_teamvision_title.ai
  resources/title_slides/ai/mtl_s02_data_ui_title.ai
  resources/title_slides/ai/mtl_s03_teamdata_title.ai
  resources/title_slides/ai/mtl_s04_teamneeds_title.ai
  resources/title_slides/ai/mtl_s05_teamworld_title.ai
  resources/title_slides/ai/mtl_s06_systems_story_title.ai
  resources/title_slides/ai/mtl_s07_base_case_title.ai
  resources/title_slides/ai/mtl_s08_dynamic_hypothesis_title.ai
  resources/title_slides/ai/mtl_s09_compare_alternatives_title.ai
  resources/title_slides/ai/mtl_s10_systems_thinking_title.ai
  resources/title_slides/ai/mtl_s11_team_decisions_title.ai
  resources/title_slides/ai/mtl_s12_team_plan_title.ai
Labels: pi

#1371 Jenn_maps_ .md
  resources/maps/maps_markdown/documentation_map.md
  resources/maps/maps_markdown/mtl_how_map.md
  resources/maps/maps_markdown/zenhub_flow.md
Labels: hq

#1388 see/say_guide_updates
  mtl_facilitate_workgroup/learner_see/mtl_session01_see.md
  mtl_facilitate_workgroup/learner_see/mtl_session02_see.md
  mtl_facilitate_workgroup/learner_see/mtl_session03_see.md
  mtl_facilitate_workgroup/learner_see/mtl_session04_see.md
  mtl_facilitate_workgroup/learner_see/mtl_session05_see.md
  mtl_facilitate_workgroup/learner_see/mtl_session06_see.md
  mtl_facilitate_workgroup/learner_see/mtl_session07_see.md
  mtl_facilitate_workgroup/learner_see/mtl_session08_see.md
  mtl_facilitate_workgroup/learner_see/mtl_session09_see.md
  mtl_facilitate_workgroup/learner_see/mtl_session10_see.md
  mtl_facilitate_workgroup/learner_see/mtl_session11_see.md
  mtl_facilitate_workgroup/learner_see/mtl_session12_see.md
Labels: facilitate
