Repository lzim/teampsd, pull requests merged in 2021-05, with the labels that each got.

#1978 Update chapter_7_open_science_framework.md
  chapter_7_open_science_framework.md
Labels: hq

#1980 Add files via upload
  resources/cheatsheets/mtl_how_osf_cheatsheet.pdf
Labels: co-i_manuscript

#1981 Delete mtl_how_osf cheatsheet.pdf
  resources/cheatsheets/mtl_how_osf cheatsheet.pdf
Labels: co-i_manuscript

#1982 Session checklists
  mtl_facilitate_workgroup/checklists/apply_fidelity_checklist.md
  mtl_facilitate_workgroup/checklists/build_fidelity_checklist.md
  mtl_facilitate_workgroup/checklists/fidelity_checklist.md
  mtl_facilitate_workgroup/checklists/inter_session_checklist.md
  mtl_facilitate_workgroup/checklists/partner_fidelity_checklist.md
  mtl_facilitate_workgroup/checklists/post_session_checklist.md
  mtl_facilitate_workgroup/checklists/pre_session_checklist.md
Labels: facilitate, hq

#1983 Update branch with Master edits.
  mtl_facilitate_workgroup/checklists/apply_fidelity_checklist.md
  mtl_facilitate_workgroup/checklists/build_fidelity_checklist.md
  mtl_facilitate_workgroup/checklists/fidelity_checklist.md
  mtl_facilitate_workgroup/checklists/inter_session_checklist.md
  mtl_facilitate_workgroup/checklists/partner_fidelity_checklist.md
  mtl_facilitate_workgroup/checklists/post_session_checklist.md
  mtl_facilitate_workgroup/checklists/pre_session_checklist.md
Labels: hq

#1984 #1074 checklist edits
  mtl_facilitate_workgroup/facilitator_say/mtl_session01_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session02_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session03_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session04_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session05_say_checklist.md
Labels: hq

#1990 Update checklists
  mtl_facilitate_workgroup/facilitator_say/mtl_session06_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session07_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session08_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session09_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session10_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session11_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session12_say_checklist.md
Labels: hq

#1991 Update mtl_session05_say_checklist.md
  mtl_facilitate_workgroup/facilitator_say/mtl_session05_say_checklist.md
Labels: hq

#1997 Update Shortlinks in Pre/Post emails
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session05.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session06.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session07.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session08.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session09.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session10.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session11.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session12.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session05.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session06.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session07.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session08.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session09.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session10.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session11.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session12.md
Labels: hq

#1999 Update janes role pre post emails
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session01.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session02.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session03.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session04.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session05.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session06.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session07.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session08.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session09.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session10.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session11.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session12.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session02.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session03.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session04.md
Labels: hq

#2018 Pre post email updates
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_part_1_wk_02.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_part_2_wk_04.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_va_red_session_01.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_va_red_session_02.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_va_red_session_03.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_va_red_session_04.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_va_red_session_05.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_va_red_session_06.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_va_red_session_07.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_va_red_session_08.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_va_red_session_09.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_va_red_session_10.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_va_red_session_11.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/email_starter_template.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session01.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session02.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session03.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session04.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session05.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session06.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session07.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session08.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session09.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session10.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session11.md
  mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_post_session12.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/email_starter_template.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session01.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session02.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session03.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session04.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session05.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session06.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session07.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session08.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session09.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session10.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session11.md
  mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session12.md
Labels: hq
