Repository lzim/teampsd, pull requests merged in 2021-03, with the labels that each got.

#1766 Update README.md
  README.md
Labels: hq

#1767 Update README.md
  README.md
Labels: hq

#1768 Update README.md
  README.md
Labels: hq

#1769 Update _bookdown.yml
  _bookdown.yml
Labels: facilitate

#1801 Add files via upload
  resources/logos/mtl_how_blue_640x420.png
  resources/logos/mtl_how_blue_650x650.png
  resources/logos/mtl_how_red_640x420.png
  resources/logos/mtl_how_red_650x650.png
Labels: hq

#1814 Pre post emails
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/.readme
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/mtl_red_part_1.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_part_1_wk_02.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_part_2_wk_04.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_wk_06.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_wk_08.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_wk_10.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_wk_12.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_wk_14.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_wk_16.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_wk_18.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_wk_20.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_wk_22.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_red_wk_24.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/mtl_red_part_1.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_red_part_1_wk_01.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_red_part_2_wk_03.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_red_wk_05.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_red_wk_07.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_red_wk_09.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_red_wk_11.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_red_wk_13.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_red_wk_15.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_red_wk_17.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_red_wk_19.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_red_wk_21.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/readme.md
Labels: facilitate

#1818 Update review pull request documentation
  chapter_11_track_issues_and_features.md
Labels: quant
