Repository lzim/teampsd, pull requests merged in 2022-05, with the labels that each got.

#2660 Feature pre post emails title session
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_nih_red_part_1.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/post_emails/post_mtl_nih_red_part_2.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_nih_red_part_1.md
  mtl_facilitate_workgroup/pre_post_emails/mtl_red_emails/pre_emails/pre_mtl_nih_red_part_2.md
Labels: hq, Operations

#2667 Feature gh pages research and development workstream edit
  4.8_onboard_new_team_member_to_va.md
  5.3_submit_vaco_and_vapahcs_progress_report.md
Labels: Development, Operations

#2443 Feature add meghana bio
  resources/bios/nallajerla_bio.md
  resources/headshots/meghana_headshot.jpeg
Labels: hq, Operations

#2460 Feature jenn mtl session plan learning objectives
  mtl_facilitate_workgroup/mtl_fidelity.md
  mtl_facilitate_workgroup/mtl_session_plan_learning_objectives.md
Labels: facilitate
